@startuml



rectangle Database

rectangle "Organisation" {
    usecase UC1 as "User defines N as Integer"

    usecase UC2 as "Get top N populated capital cities in world"

    usecase UCa as "Name, Country, Population"
}
    User - UC1
    UC1 ..> UC2
    UC2 ..> UCa : include
    UC2 - Database


@enduml