@startuml



rectangle Database

rectangle "Organisation" {
    usecase UC1 as "User defines N as Integer"

    usecase UC2 as "Get top N populated countries in region"

    usecase UCa as "Print: Code, Name, Continent,
    Region, Population, Capital"
}
    User - UC1
    UC1 ..> UC2
    UC2 ..> UCa : include
    UC2 - Database


@enduml