@startuml



rectangle Database

rectangle "Organisation" {
    usecase UC1 as "Get population, city population %,
    non-city population % in country"

    usecase UCa as "Print: country name, country population,
    city population % , non-city population %"
}
    User - UC1
    UC1 ..> UCa : include
    UC1 - Database


@enduml
