@startuml



rectangle Database

rectangle "Organisation" {
    usecase UC1 as "Get population in country"

    usecase UCa as "Print country population "
}
    User - UC1
    UC1 ..> UCa : include
    UC1 - Database


note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml